services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev_runner
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - mongo